lucky:
  jdbc:
    defaultDB: ##定位数据源
      pool-type: HikariCP #创建数据源
      url: jdbc:mysql://127.0.0.1:3306/test-2?useUnicode=true&characterEncoding=utf-8&useSSL=true&useTimezone=true&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      log: true
      format-sql-log: false
      show-complete-sql: true
      cache: false
      cache-expired-time: 缓存的过期时间
      cache-capacity: 50
      auto-create-tables:
        - com.lucky.jacklamb.test.Book
#        - com.lucky.jacklamb.exception.DatabaseTypeUnableIdentifyException
#        - com.jacklamb.lucky.entity.Authod
      reverse-package: com.jacklamb.lucky.pojo
      project-path: C:\Users\DELL\git\lucky-ex\src\

      ##HikariCP专属配置
#      data-source-class-name: String
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 600001
      max-life-time: 1800001
#      connection-test-query: String
      minimum-idle: 34
      maximum-pool-size: 10
#      pool-name: String
      #      metric-registry: Object
      #      health-check-registry: Properties
      initialization-fail-timeout: 23
      isolate-internal-queries: false
      allow-pool-suspension: false
      read-only: false
      register-mbeans: true
#      catalog: String
#      connection-init-sql: String
#      transaction-isolation: String
      validation-timeout: 5000
      leakdetection-threshold: 0
      #      data-source: DataSource
#      schema: String
#      thread-factory: ThreadFactory
#      scheduled-executor-service: ScheduledExecutorService

jacklamb:
  mapper-xml: classpath:/mapper2/