lucky:
  jdbc:
    defaultDB: ##定位数据源
      pool-type: HikariCP #创建数据源
      url: jdbc:mysql://127.0.0.1:3306/jacklamb?useUnicode=true&characterEncoding=utf-8&useSSL=true&useTimezone=true&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      log: false
      format-sql-log: false
      shwo-complete-sql: false
      cache: false
      cache-expired-time: 缓存的过期时间
      cache-capacity: 50
      auto-create-tables:
        - com.lucky.jacklamb.exception.CreateMapperException
        - com.lucky.jacklamb.exception.DatabaseTypeUnableIdentifyException
        - com.jacklamb.lucky.entity.Authod
      reverse-package: com.jacklamb.lucky.pojo
      project-path: C:\Users\DELL\git\lucky-ex\src\

      ##HikariCP专属配置
      data-source-class-name: String
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 23
      max-life-time: 34
      connection-test-query: String
      minimum-idle: 34
      maximum-pool-size: 45
      pool-name: String
#      metric-registry: Object
#      health-check-registry: Properties
      initialization-fail-timeout: 23
      isolate-internal-queries: false
      allow-pool-suspension: false
      read-only: false
      register-mbeans: true
      catalog: String
      connection-init-sql: String
      transaction-isolation: String
      validation-timeout: 11
      leakdetection-threshold: 32
#      data-source: DataSource
      schema: String
#      thread-factory: ThreadFactory
#      scheduled-executor-service: ScheduledExecutorService