server:
  ##启动端口
  port: 8080
  ##项目路径
  context-path: \"\"
  ##session超时时间（分钟）
  session-timeout: 30
  ##静态文件所在的文件夹
  doc-base: classpath:/templates/
  ##tomcat运行时临时文件所在的文件夹（默认在系统的临时文件夹）
  base-dir: java.io.tmpdir:/tomcat.${port}/
  webapp: /WebContent/
  ##webapps目录中增加新的目录、war文件、修改WEB-INF/web.xml，autoDeploy="true"会新建或重新部署应用
  auto-deploy: false
  ##替换WEB-INF/lib目录中的jar文件或WEB-INF/classes目录中的class文件时，reloadable="true"会让修改生效
  reloadable: false
  ##关闭端口
  close-port: 8005
  ##关闭命令
  shutdown: SHUTDOWN
  ##URL编码
  url-encoding: UTF-8
  tomcat:
    #最小线程数
    min-spare-threads: 500
    #最大线程数
    max-threads: 2500
    #最大链接数
    max-connections: 6500
    #连接超时时间
    connection-timeout: 12000
    #最大等待队列长度
    accept-count: 1000
    #请求头最大长度kb
    max-http-header-size: 1048576
    #请请求体最大长度kb
    max-save-post-size: 2097152
  ##配置Servlet
  servlets:
    - servlet-name: ServletName #Servlet名字
      servlet-class: org.jack.servlet.MyServlet #Servlet的全限定类名
      url-patterns: [/,/user/] #监听的路径
      load-on-startup: -1 #初始化方法执行的优先级，大于0表示在服务器启动时初始化该Servlet
      async-supported: false #是否支持异步
      init-params: #配置参数
        k1: v1
        k2: v2
    - servlet-name: ServletName2
      servlet-class: org.jack.servlet.MyServlet
      url-patterns: [/,/user/]
      load-on-startup: -1
      async-supported: false
      init-params:
        k1: v1
        k2: v2
  ##配置Filter
  filters:
    - filter-name: filterName #Filter名字
      filter-class: org.jack.servlet.MyFilter #Filter的全限定类名
      url-patterns: [/*,/user/*] #监听的路径
      servlet-names: [servletName1,servletName2] #监听的Servlet
      async-supported: false #是否支持异步
      dispatcher-types: [FORWARD,INCLUDE,REQUEST,ASYNC,ERROR] #调度的类型
      init-params: #配置参数
        k1: v1
        k2: v2

    - filter-name: filterName2
      filter-class: org.jack.servlet.MyFilter
      url-patterns: [/*,/user/*]
      servlet-names: [servletName1,servletName2]
      async-supported: false
      dispatcher-types: [FORWARD,INCLUDE,REQUEST,ASYNC,ERROR]
      init-params:
        k1: v1
        k2: v2

  listeners:
    listenerName: class


