lucky:
  #lucky-web配置
  web:
    #URL编码格式
    encoding: UTF-8
    ##静态文件的根目录
    #classpath}:/xxx/ ：classpath下的某个文件夹 默认：${classpath}/webapps
    #user.dir:/xxx/  ：System.getProperty("user.dir")下的某个文件夹
    #docBase:/xxx/   : Tomcat的docBase下的某个文件夹
    ##绝对路径
    web-root: classpath:/templates/
    #是否开启POST请求类型转换(_method)
    post-change-method: false
    #是否开启静态资源管理器
    static-resource-manage: false
    #[文件上传]设置单个文件大小限制，单位：KB
    multipart-max-file-size: 1204
    #[文件上传]设置总文件大小为限制，单位：KB
    multipart-max-request-size: 10*1024
    #json序列化方案
    serialization:
      xml : com.lucky.framework.serializable.implement.XtreamSerializationScheme
      json: com.lucky.framework.serializable.implement.GsonSerializationScheme
    #错误页面配置
    error-page:
      404: /lucky-web/404.html
      500: /lucky-web/404.html
    #favicon.ico文件
    favicon-ico: /lucky-web/favicon.ico
    #全局资源前缀
    prefix: /WEN-INF/
    #全局资源后缀
    suffix: .html
    #httpclient连接超时时间（ms）
    httpclient-connection-timeout: 5000
    #httpclient连接请求超时时间(ms)
    httpclient-request-timeout: 5000
    #httpclientsocket超时时间(ms)
    httpclient-socket-timeout: 5000
    #静态资源映射，将某个静态资源映射到一个特定的URL上
    static-handler:
      /user/login  : /user/login.html
      /admin/update: /admin/update.html
    #全局资源IP限制
    global-resources-restrict-ip:
      - 192.168.3.3
      - 192.168.3.4
    #静态资源Ip限制
    static-resources-restrict-ip:
      - 192.168.3.3
      - 192.168.3.4
    #指定资源的Ip限制,一个资源只能被指定的ip访问
    specifi-resources-restrict-ip:
      /user/query/  : [192.168.3.3,192.168.3.4]
      /file/test.jpg: [192.168.3.3,192.168.3.4]